name = "M_blas"
version = "0.1.0"
license = "MIT"
author = "John Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2021, John Urban"
description = "BLAS"
categories = ["linear algebra", "fortran", "General Purpose Fortran"]
keywords = ["linear-algebra", "BLAS", "fortran", "fpm" ]
homepage = "https://github.com/urbanjost"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = true
